#!/bin/bash

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

cd ${WEBROOT}
git pull || exit 1

# Try auto install for composer
if [ -f "${COMPOSERROOT}/composer.lock" ]; then
  composer install --working-dir=${COMPOSERROOT}
fi

#echo "updating .env file with your information.."
#printf "APP_ENV=%s\n APP_SECRET=%s\n DATABASE_URL=mysql://%s:%s@%s:3306/%s?serverVersion=5.7" "$APPLICATION_ENV" "$APPLICATION_SECRET" "$DB_USERNAME" "$DB_PASSWORD" "$DB_HOST" "$DB_DATABASE" > /var/www/html/src/.env

cd ${COMPOSERROOT}
echo "Updating database..."
php bin/console doctrine:schema:update --force

echo "Installing bundled assets..."
php bin/console assets:install public

echo "Clearing Symfony cache..."
php bin/console cache:clear

chown -Rf nginx:nginx ${WEBROOT}